# frozen_string_literal: true

module Reqcord
  module Exporters
    class Markdown
      def self.call(dataset:, output_dir:, configuration:)
        new(
          dataset: dataset,
          output_dir: output_dir,
          configuration: configuration
        ).call
      end

      def initialize(dataset:, output_dir:, configuration:)
        @dataset = dataset
        @output_dir = Pathname(output_dir)
        @configuration = configuration
      end

      # Returns every written path.
      def call
        FileUtils.mkdir_p(output_dir)

        written = [write(output_dir.join("README.md"), index_document)]

        written_resources.each do |resource|
          directory = output_dir.join(resource.slug)

          FileUtils.mkdir_p(directory)

          written << write(
            directory.join("index.md"),
            resource_document(resource)
          )

          filenames(resource).each do |endpoint, filename|
            next unless documented?(endpoint)

            written << write(
              directory.join(filename),
              endpoint_document(resource, endpoint)
            )
          end
        end

        written
      end

      private

      attr_reader :dataset, :output_dir, :configuration

      # An endpoint gets a page when a test reached it, or when the project
      # asked for the gaps to be written out too.
      def documented?(endpoint)
        endpoint.curl_ready? || configuration.include_uncovered?
      end

      # A resource with nothing to show gets no directory, so the index never
      # links to a page that was not written.
      def written_resources
        @written_resources ||= dataset.resources.select do |resource|
          resource.endpoints.any? { |endpoint| documented?(endpoint) }
        end
      end

      def written?(resource)
        written_resources.include?(resource)
      end

      def write(path, content)
        File.write(path, content)

        path.to_s
      end

      def filenames(resource)
        resource.file_basenames.transform_values { |basename| "#{basename}.md" }
      end

      def index_document
        lines = ["# API Documentation", ""]
        lines << "Generated by Reqcord from the application's integration tests."
        lines << ""
        lines << "Base URL: `#{configuration.base_url}`"
        lines << ""
        lines.concat(placeholders_section)

        dataset.resources.each do |resource|
          lines << if written?(resource)
                     "## [#{resource.title}](#{resource.slug}/index.md)"
                   else
                     "## #{resource.title}"
                   end
          lines << ""
          lines.concat(namespace_line(resource))
          lines.concat(endpoint_table(resource, prefix: "#{resource.slug}/"))
          lines << ""
        end

        undocumented = dataset.endpoints.reject(&:curl_ready?)

        unless undocumented.empty?
          lines << "## No Successful Request Captured"
          lines << ""
          lines << "No successful 2xx request was captured for these routes:"
          lines << ""
          undocumented.each { |endpoint| lines << "- `#{endpoint.method} #{endpoint.path}`" }
          lines << ""
        end

        lines.join("\n")
      end

      # Sanitized values are written as placeholders; the reader has to know
      # what to substitute.
      def placeholders_section
        placeholders = configuration.sanitized_headers.values.grep(/\{\{.+\}\}/)

        return [] if placeholders.empty?

        rows = configuration.sanitized_headers.filter_map do |header, value|
          "| #{header} | `#{value}` |" if value.to_s.match?(/\{\{.+\}\}/)
        end

        ["## Placeholders", "", "| Header | Replace with |", "| --- | --- |", *rows, ""]
      end

      # Two resources can share a title (admin/customers, api/v2/customers);
      # the namespace tells them apart.
      def namespace_line(resource)
        return [] if resource.namespace.empty?

        ["Namespace: `#{resource.namespace}`", ""]
      end

      def resource_document(resource)
        lines = ["# #{resource.title}", ""]
        lines.concat(namespace_line(resource))

        versions = resource.api_versions

        unless versions.empty?
          lines << "API version: #{versions.map { |version| "`#{version}`" }.join(', ')}"
          lines << ""
        end

        lines.concat(endpoint_table(resource))
        lines << ""
        lines.join("\n")
      end

      def endpoint_table(resource, prefix: "")
        rows = filenames(resource).map do |endpoint, filename|
          path =
            if documented?(endpoint)
              "[`#{endpoint.path}`](#{prefix}#{filename})"
            else
              "`#{endpoint.path}`"
            end

          covered = endpoint.curl_ready? ? "" : " _(no successful request captured)_"

          "| `#{endpoint.method}` | #{path} | #{endpoint.name}#{covered} |"
        end

        ["| Method | Path | Description |", "| --- | --- | --- |", *rows]
      end

      def endpoint_document(resource, endpoint)
        example = endpoint.primary_request_example

        lines = ["# #{endpoint.name}", "", endpoint_line(endpoint), ""]
        lines.concat(namespace_line(resource))

        unless endpoint.curl_ready?
          lines << "_No successful 2xx request was captured for this endpoint yet._"
          lines << ""
        end

        lines.concat(headers_section(example))
        lines.concat(schema_section("Path Parameters", endpoint.path_param_schema))
        lines.concat(schema_section("Query Parameters", endpoint.query_schema))
        lines.concat(schema_section("Body Parameters", endpoint.body_schema))
        lines.concat(request_body_section(example))
        lines.concat(curl_section(example))
        lines.concat(responses_section(endpoint))
        lines.concat(["---", "", "Resource: [#{resource.title}](index.md)", ""])

        lines.join("\n")
      end

      # Field, type, whether every accepted request carried it, and the values
      # those requests used. Values are listed only when they look like a
      # closed set; otherwise one of them stands as an example.
      def schema_section(title, schema, level: 2)
        return [] if schema.empty?

        rows = schema.map do |field|
          "| `#{field.path}` | #{field.type} | #{field.required? ? 'yes' : 'no'} | #{values_cell(field)} |"
        end

        ["#{'#' * level} #{title}", "", "| Field | Type | Required | Values |", "| --- | --- | --- | --- |", *rows, ""]
      end

      def values_cell(field)
        return "-" if field.values.empty?
        return field.listed_values.map { |value| "`#{value.inspect}`" }.join(" \\| ") if field.enum?

        "`#{field.example.inspect}`"
      end

      # `PATCH /api/cart` (also `PUT`)
      def endpoint_line(endpoint)
        line = "`#{endpoint.method} #{endpoint.path}`"

        return line if endpoint.also_methods.empty?

        "#{line} (also #{endpoint.also_methods.map { |method| "`#{method}`" }.join(', ')})"
      end

      def headers_section(example)
        return [] if example.nil? || example.headers.empty?

        rows = example.headers.map { |name, value| "| #{name} | `#{value}` |" }

        ["## Headers", "", "| Header | Value |", "| --- | --- |", *rows, ""]
      end

      # A form body is shown as the key/value structure the test built, which
      # reads better than the encoded string; the note says how it travels.
      def request_body_section(example)
        return [] unless example&.body?

        lines = ["## Example Request", ""]

        unless Renderers::Payload.json?(example) || example.content_type.to_s.empty?
          lines << "Sent as `#{example.content_type}`; the cURL below carries it in that encoding."
          lines << ""
        end

        lines.concat([*code_block(example.body, example.content_type), ""])
      end

      def curl_section(example)
        return [] if example.nil?

        ["## cURL", "", "```bash", curl_for(example), "```", ""]
      end

      def responses_section(endpoint)
        return [] if endpoint.response_examples.empty?

        lines = ["## Responses", ""]

        endpoint.responses.each do |response|
          lines << "### #{response.example.title}"
          lines << ""
          lines.concat(schema_section("Fields", response.schema, level: 4))
          lines.concat(response_body(response.example))
        end

        lines
      end

      def response_body(example)
        return ["_No response body._", ""] unless example.body?

        [*code_block(example.body, example.content_type), ""]
      end

      def curl_for(example)
        Renderers::Curl.call(
          example,
          base_url: configuration.base_url
        )
      end

      def code_block(value, content_type)
        case value
        when Hash, Array then ["```json", pretty_json(value), "```"]
        else ["```#{content_type.to_s.include?('json') ? 'json' : 'text'}", value.to_s, "```"]
        end
      end

      def pretty_json(value)
        JSON.pretty_generate(value)
      rescue JSON::GeneratorError
        value.to_s
      end
    end

    register("markdown", Markdown)
  end
end
