# frozen_string_literal: true

module Reqcord
  module Exporters
    # Writes an OpenAPI 3.1 document (`openapi/openapi.json`) from the dataset:
    # one path item per documented route, parameters and request bodies from
    # the inferred schemas, one response per captured status with its example,
    # and security schemes derived from the sanitized credential headers. This
    # is what Scalar (via Reqcord::Web), Swagger UI or Redoc render.
    class Openapi
      OPENAPI_VERSION = "3.1.0"
      DYNAMIC_SEGMENT = /[:*]([a-zA-Z_][a-zA-Z0-9_]*)/
      BEARER = /\ABearer\s+/i

      def self.call(dataset:, output_dir:, configuration:)
        new(
          dataset: dataset,
          output_dir: output_dir,
          configuration: configuration
        ).call
      end

      def initialize(dataset:, output_dir:, configuration:)
        @dataset = dataset
        @output_dir = Pathname(output_dir).join("openapi")
        @configuration = configuration
      end

      def call
        FileUtils.mkdir_p(output_dir)

        path = output_dir.join("openapi.json")
        File.write(path, "#{JSON.pretty_generate(document)}\n")

        [path.to_s]
      end

      def document
        {
          openapi: OPENAPI_VERSION,
          info: {
            title: "#{File.basename(configuration.root.to_s)} API",
            version: api_version,
            description: "Generated by Reqcord from the application's integration tests."
          },
          servers: [{ url: configuration.base_url }],
          tags: tags,
          paths: paths,
          components: components
        }.reject { |_key, value| value.nil? || (value.respond_to?(:empty?) && value.empty?) }
      end

      private

      attr_reader :dataset, :output_dir, :configuration

      # A single API version across the dataset names the document; mixed
      # versions fall back to a neutral one.
      def api_version
        versions = dataset.curl_ready_endpoints.map(&:api_version).compact.uniq

        versions.size == 1 ? versions.first : "1.0.0"
      end

      def tags
        dataset.resources
               .select { |resource| resource.endpoints.any?(&:curl_ready?) }
               .map { |resource| { name: resource.title, description: resource.name }.compact }
      end

      def paths
        dataset.resources.each_with_object({}) do |resource, result|
          resource.endpoints.each do |endpoint|
            next unless endpoint.curl_ready?
            next if endpoint.method == RouteCollector::ANY

            path_variants(endpoint.path).each do |oas_path|
              result[oas_path] ||= {}
              result[oas_path][endpoint.method.downcase] = operation(endpoint, oas_path, resource)
            end
          end
        end
      end

      # `/items(/:id)` is two OpenAPI paths: `/items` and `/items/{id}`.
      def path_variants(pattern)
        required = pattern.gsub(/\([^()]*\)/, "")
        expanded = pattern.tr("()", "")

        [required, expanded].uniq.map { |path| path.gsub(DYNAMIC_SEGMENT, '{\1}') }
      end

      def operation(endpoint, oas_path, resource)
        example = endpoint.primary_request_example

        {
          operationId: operation_id(endpoint, oas_path),
          summary: endpoint.name,
          description: description(endpoint),
          tags: [resource.title],
          parameters: path_parameters(endpoint, oas_path) + query_parameters(endpoint),
          requestBody: request_body(endpoint, example),
          responses: responses(endpoint),
          security: security_for(example)
        }.reject { |_key, value| value.nil? || (value.respond_to?(:empty?) && value.empty?) }
      end

      def operation_id(endpoint, oas_path)
        Support.parameterize("#{endpoint.method} #{oas_path.tr('{}', '')}").tr("-", "_")
      end

      def description(endpoint)
        lines = ["#{endpoint.controller}##{endpoint.action}"]
        lines << "Also answers #{endpoint.also_methods.join(', ')}." unless endpoint.also_methods.empty?
        lines << "Route: #{endpoint.route_name}" if endpoint.route_name

        lines.join("\n")
      end

      def path_parameters(endpoint, oas_path)
        oas_path.scan(/\{([^}]+)\}/).flatten.map do |name|
          field = endpoint.path_param_schema[name]

          {
            name: name,
            in: "path",
            required: true,
            schema: field ? scalar_schema(field) : { type: "string" },
            example: field&.example
          }.compact
        end
      end

      # `filter.category` was captured as Rails' `filter[category]`.
      def query_parameters(endpoint)
        endpoint.query_schema.map do |field|
          {
            name: query_name(field.path),
            in: "query",
            required: field.required?,
            schema: scalar_schema(field),
            example: field.example
          }.compact
        end
      end

      def query_name(path)
        head, *rest = path.split(".")

        head + rest.map { |segment| "[#{segment}]" }.join
      end

      def request_body(endpoint, example)
        return nil if endpoint.body_schema.empty?

        content_type =
          if Renderers::Payload.multipart?(example)
            "multipart/form-data"
          elsif Renderers::Payload.json?(example)
            "application/json"
          else
            "application/x-www-form-urlencoded"
          end

        # A file part is shown by name in the example; the bytes are not data.
        body = Renderers::Payload.display_body(example) { |file| FileValue.filename(file) }

        {
          required: true,
          content: {
            content_type => { schema: json_schema(endpoint.body_schema), example: body }.compact
          }
        }
      end

      def responses(endpoint)
        endpoint.responses.each_with_object({}) do |response, result|
          example = response.example
          entry = { description: example.status_text }

          if example.body?
            content_type = example.content_type.to_s.empty? ? "application/json" : example.content_type
            entry[:content] = { content_type => { schema: json_schema(response.schema), example: example.body }.compact }
          end

          result[response.status.to_s] = entry
        end
      end

      # --- schemas ----------------------------------------------------------

      # Turns the flattened field list (`customer.items[].sku`) back into a
      # JSON Schema tree. A leaf every accepted request carried is required,
      # and so is every object on the way down to it.
      def json_schema(schema)
        return nil if schema.empty?

        root = {}

        schema.each do |field|
          node = root

          segments_for(field.path).each do |segment|
            if segment == :array
              node[:type] = "array"
              node[:items] ||= {}
              node = node[:items]
            else
              node[:type] = "object"
              node[:properties] ||= {}
              node[:properties][segment] ||= {}
              node[:required] = (node[:required] || []) | [segment] if field.required?
              node = node[:properties][segment]
            end
          end

          node.merge!(scalar_schema(field)) if node.empty?
        end

        root
      end

      # "customer.items[].sku" -> ["customer", "items", :array, "sku"];
      # "[].id" -> [:array, "id"]
      def segments_for(path)
        path.split(".").flat_map do |part|
          name, brackets = part.match(/\A([^\[\]]*)((?:\[\])*)\z/).captures
          pieces = []
          pieces << name unless name.empty?
          pieces.concat([:array] * (brackets.length / 2))
          pieces
        end
      end

      def scalar_schema(field)
        types = field.types.to_a.sort
        return { type: "string", format: "binary" } if types == ["file"]

        schema = { type: types.size == 1 ? types.first : types }
        schema[:enum] = field.listed_values if field.enum?
        schema[:example] = field.example unless field.example.nil?

        schema
      end

      # --- security ---------------------------------------------------------

      def components
        schemes = {}
        schemes[:bearerAuth] = { type: "http", scheme: "bearer" } if bearer_used?
        schemes[:apiKeyAuth] = { type: "apiKey", in: "header", name: api_key_header } if api_key_header

        schemes.empty? ? nil : { securitySchemes: schemes }
      end

      def security_for(example)
        requirements = []
        requirements << { bearerAuth: [] } if bearer?(example)
        requirements << { apiKeyAuth: [] } if api_key_header && header(example, api_key_header)

        requirements
      end

      def bearer_used?
        documented_examples.any? { |example| bearer?(example) }
      end

      def bearer?(example)
        header(example, "Authorization").to_s.match?(BEARER)
      end

      # The first API-key style header the sanitizer knows about that a
      # documented request actually carried.
      def api_key_header
        return @api_key_header if defined?(@api_key_header)

        candidates = configuration.sanitized_headers.keys.reject { |name| name.casecmp?("Authorization") }

        @api_key_header = candidates.find do |name|
          documented_examples.any? { |example| header(example, name) }
        end
      end

      def header(example, name)
        example.headers.find { |key, _| key.to_s.casecmp?(name) }&.last
      end

      def documented_examples
        @documented_examples ||= dataset.curl_ready_endpoints.map(&:primary_request_example)
      end
    end

    register("openapi", Openapi)
  end
end
