# frozen_string_literal: true

module Reqcord
  module Exporters
    # Writes a Postman Collection v2.1 (`postman/collection.json`). Folders
    # follow the controller namespaces, each documented endpoint is one request
    # built from the successful captured example, and every captured status
    # is saved as a response example. Hoppscotch imports the same file.
    class Postman
      SCHEMA_URL = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
      PLACEHOLDER = /\{\{([A-Za-z0-9_]+)\}\}/
      BEARER = /\ABearer\s+\{\{([A-Za-z0-9_]+)\}\}\z/i

      def self.call(dataset:, output_dir:, configuration:)
        new(
          dataset: dataset,
          output_dir: output_dir,
          configuration: configuration
        ).call
      end

      def initialize(dataset:, output_dir:, configuration:)
        @dataset = dataset
        @output_dir = Pathname(output_dir).join("postman")
        @configuration = configuration
      end

      def call
        FileUtils.mkdir_p(output_dir)

        path = output_dir.join("collection.json")
        File.write(path, "#{JSON.pretty_generate(collection)}\n")

        [path.to_s]
      end

      def collection
        {
          info: {
            name: "#{File.basename(configuration.root.to_s)} API",
            description: "Generated by Reqcord from the application's integration tests.",
            schema: SCHEMA_URL
          },
          item: folders,
          variable: variables,
          auth: auth
        }.compact
      end

      private

      attr_reader :dataset, :output_dir, :configuration

      # api/v2/customers -> Api > V2 > Customers, requests in the leaf folder.
      def folders
        tree = { items: [], children: {} }

        dataset.resources.each do |resource|
          requests = resource.endpoints.select(&:curl_ready?).map { |endpoint| request_item(endpoint) }
          next if requests.empty?

          leaf = resource.segments.reduce(tree) do |node, segment|
            node[:children][segment] ||= { items: [], children: {} }
          end

          leaf[:items].concat(requests)
        end

        render_folders(tree)
      end

      def render_folders(node)
        node[:children].map do |segment, child|
          { name: Support.titleize(segment), item: render_folders(child) + child[:items] }
        end
      end

      def request_item(endpoint)
        {
          name: endpoint.name,
          request: request_object(endpoint.primary_request_example, endpoint),
          response: endpoint.responses.map { |response| response_object(response, endpoint) }
        }
      end

      def request_object(example, endpoint)
        {
          method: example.method,
          description: description(endpoint),
          header: headers(example),
          url: url_object(example),
          body: body_object(example),
          auth: request_auth(example)
        }.compact
      end

      def description(endpoint)
        lines = ["#{endpoint.method} #{endpoint.path}", "#{endpoint.controller}##{endpoint.action}"]
        lines << "Also answers #{endpoint.also_methods.join(', ')}." unless endpoint.also_methods.empty?
        lines << "Route: #{endpoint.route_name}" if endpoint.route_name

        lines.join("\n")
      end

      # The bearer credential lives on the collection; a request that carried
      # it inherits, one that did not says so, so public endpoints replay
      # exactly as their tests did.
      def headers(example)
        example.headers.filter_map do |key, value|
          next if auth && key.to_s.casecmp?("Authorization")

          { key: key.to_s, value: value.to_s }
        end
      end

      def request_auth(example)
        return nil unless auth
        return nil if example.headers.any? { |key, _| key.to_s.casecmp?("Authorization") }

        { type: "noauth" }
      end

      def url_object(example)
        url = {
          raw: "{{base_url}}#{Renderers::Payload.path_with_query(example)}",
          host: ["{{base_url}}"],
          path: example.path.split("/").reject(&:empty?),
          query: Renderers::Payload.query_pairs(example).map { |key, value| { key: key, value: value.to_s } }
        }

        url.delete(:query) if url[:query].empty?
        url
      end

      def body_object(example)
        return nil unless example.body?

        if Renderers::Payload.multipart?(example)
          parts = Renderers::Payload.form_pairs(example).map do |key, value|
            if FileValue.file?(value)
              { key: key, type: "file", src: FileValue.filename(value) }
            else
              { key: key, value: value.to_s, type: "text" }
            end
          end

          { mode: "formdata", formdata: parts }
        elsif Renderers::Payload.json?(example)
          { mode: "raw", raw: Renderers::Payload.raw_body(example), options: { raw: { language: "json" } } }
        elsif example.body.is_a?(Hash)
          pairs = Renderers::Payload.form_pairs(example).map { |key, value| { key: key, value: value.to_s, type: "text" } }

          { mode: "urlencoded", urlencoded: pairs }
        else
          { mode: "raw", raw: example.body.to_s }
        end
      end

      def response_object(response, endpoint)
        example = response.example
        request = endpoint.request_examples.find { |candidate| candidate.response_status == response.status } ||
                  endpoint.primary_request_example

        {
          name: example.title,
          originalRequest: request_object(request, endpoint),
          status: example.status_text,
          code: response.status,
          _postman_previewlanguage: example.content_type.to_s.include?("json") ? "json" : "text",
          header: example.headers.map { |key, value| { key: key.to_s, value: value.to_s } },
          body: response_body(example)
        }
      end

      def response_body(example)
        return "" unless example.body?
        return example.body if example.body.is_a?(String)

        JSON.pretty_generate(example.body)
      end

      # `base_url`, plus every `{{name}}` the sanitizer wrote into the
      # documented examples, so the collection declares what it expects.
      def variables
        names = documented_examples.flat_map do |example|
          [example.headers, example.body, example.query_params].flat_map do |value|
            JSON.generate(value).scan(PLACEHOLDER).flatten
          end
        end

        names |= (configuration.sanitized_headers.values + configuration.sanitized_body_keys.values)
                 .flat_map { |value| value.to_s.scan(PLACEHOLDER).flatten }

        [{ key: "base_url", value: configuration.base_url, type: "string" }] +
          (names - ["base_url"]).uniq.sort.map { |name| { key: name, value: "", type: "string" } }
      end

      def auth
        return @auth if defined?(@auth)

        placeholder = documented_examples.filter_map do |example|
          value = example.headers.find { |key, _| key.to_s.casecmp?("Authorization") }&.last
          value.to_s[BEARER, 1]
        end.first

        @auth = placeholder && { type: "bearer", bearer: [{ key: "token", value: "{{#{placeholder}}}", type: "string" }] }
      end

      def documented_examples
        @documented_examples ||= dataset.curl_ready_endpoints.flat_map(&:request_examples)
      end
    end

    register("postman", Postman)
  end
end
